#!/usr/bin/env bash

inputs=ner-input-files
traces=ner-trace-files

ant > build.txt
if [ $? -eq 0 ]; then
    rm build.txt

    featureTypes="WORD"
    testFeature="WORD"
    for i in "$@"; do
        if [[ $i = test=* ]]; then
            i=${i#test=}
            testFeature=$i
        fi

        featureTypes="$featureTypes $i"
    done

    echo "Features are $featureTypes"
    echo "Testing $testFeature"

    java -jar target/nlp_hw3.jar $inputs/train.txt $inputs/test.txt $inputs/locs.txt $featureTypes
    diff train.txt.readable "$traces/train.txt.readable.$testFeature" > diff.txt

    lines=`cat diff.txt | wc -l`
    if [ $lines -le 10 ]; then
        cat diff.txt
    else
        echo 'There may be some errors.'
    fi
else
    echo 'Build failed.'
    cat build.txt
    rm build.txt
fi

